---
title: "Mini-Project 3: The Road Not Taken"
author: "Jay-Ho Chung, Nathan Ives, Brigitte Goeler-Slough"
date: "4/13/2018"
output: 
    html_document:
    theme: spacelab
    df_print: paged
    code_folding: hide
---

```{r Packaages, message=FALSE, warning=FALSE}
library(sf)
library(macleish)
library(leaflet)
library(tidyverse)
library(viridisLite)
```

```{r Identifying Quickly}
macleish_layers[["trails"]] # 15 trails, geometry: Linestring, projection is longlat
```

```{r}
trails <- macleish_layers[["trails"]] %>% 
  mutate(length = st_length(geometry)) %>% 
  group_by(name) %>% 
  summarize(total_length = sum(length))

leaflet() %>% 
  addTiles() %>% 
  addPolylines(data = trails, popup = ~name)
```

```{r, eval=FALSE}
url <- "http://download.massgis.digital.mass.gov/shapefiles/state/contours250k.zip"
local_file <- basename(url)
download.file(url, destfile = local_file)
unzip(local_file)
```

```{r, eval = FALSE}
boundary <- macleish_layers[["boundary"]]
contour <- st_read("CONTOURS250K_ARC.shp") %>%
  st_transform(4326)
contour
macleish_trail <- st_intersects(boundary, contour)
```

```{r, eval = FALSE}
contour %>%
  select(CONTOUR_FT) %>%
  plot()
```

```{r, eval = FALSE}
leaflet() %>% 
  addTiles() %>% 
  addPolygons(data = boundary)
# macleish_trail %>% 
#   plot()
```

```{r}
hiking_trails <- macleish_layers[["trails"]] %>%
  mutate(lengt = st_length(geometry)) %>% 
  group_by(name) %>% 
  mutate(t_length = sum(lengt))

pal <- colorNumeric(
  palette = "viridis",
  domain = hiking_trails$t_length
)

leaflet(data = hiking_trails) %>%
  addTiles() %>%
  addPolylines(color = ~pal(t_length)) %>%
  addLegend("bottomright", pal = pal, values = ~t_length, title = "Trail Length", labFormat = labelFormat(suffix =  "m"))
```

```{r}
leaflet() %>%
  addTiles() %>%
  addPolylines(data = macleish_layers[["trails"]], color = "black", weight = 3, opacity = .5) %>%
  addPolylines(data = macleish_layers[["contours_3m"]], weight = 1, opacity = .5)
```

```{r}
m3_contour <- macleish_layers[["contours_3m"]] %>% 
  select(ELEV_M, ELEV_FT, INDEX_ARC, SHAPE_LEN, geometry)
```

```{r}
macleish_cont <- st_intersects(trails,
                               macleish_layers[["contours_3m"]])
cont_data <- st_join(trails, m3_contour)

contour_data <- cont_data %>% 
  group_by(name) %>% 
  summarize(low = min(ELEV_FT), high = max(ELEV_FT),
            change = high - low)

pal1 <- colorNumeric(
  palette = "viridis",
  domain = contour_data$change
)

leaflet(contour_data) %>% 
  addTiles() %>% 
  # addPolylines(data = trails) %>% 
  addPolylines(data = contour_data, color = ~pal1(change),
               label = ~name) %>% 
  addLegend("bottomright", pal = pal1, 
            values = ~change, 
            title = "Trail Change in Elevation",
            labFormat = labelFormat(suffix = " ft."))
```

```{r}
cont_trail <- st_join(trails, contour_data, join = st_within) %>% 
  mutate(diff_level = change / total_length)
  # group_by(name.x)
```



```{r}
cont_trail <- st_join(trails, contour_data, join = st_within) %>% 
  mutate(hard_meas = sqrt(2*(contour_data$change)*(trails$total_length))) %>%
  arrange(desc(hard_meas))
```

IDEA: Total elevation change / trail length
Also include layers and see how many times each trail intersects with the contours

Also maybe should think about getting units to be the same and maybe thinking of better measure of what makes a trail hard


```{r (Combing Trails and Contour)}
trail_cont <- st_join(trails, contour_data, join = st_within , suffix = c("name" = "name")) %>% # st_within is the join type
  mutate(hard_meas = sqrt(2*(contour_data$change*3.28084)*(trails$total_length*0.000621371))) %>% # Using the equation from the National Park Service
  mutate(level = cut(hard_meas, 
                          breaks = c(-Inf, 5, 22, Inf), 
                          labels = c("Easy", "Medium", "Hard"))) %>% 
  select(nameNA , change , total_length , hard_meas, level) %>%
  arrange((hard_meas)) %>% # Want to arrange it
  rename("name" = "nameNA")
```

res <- df %>% mutate(category=cut(a, breaks=c(-Inf, 0.5, 0.6, Inf), labels=c("low","middle","high")))

```{r}
easy_trail <- trail_cont %>% 
  filter(level == "Easy")

medium_trail <- trail_cont %>% 
  filter(level == "Medium")

hard_trail <- trail_cont %>% 
  filter(level == "Hard")
```


```{r}
qpal <- colorFactor(c("green", "yellow", "red"), 
                     domain = trail_cont$level) # Assignig a color factor. to the difficulty.

leaflet(data = trail_cont) %>%
  addTiles(group = "OpenStreetMap") %>%
  addProviderTiles("Esri.WorldTopoMap", group = "Topography") %>%
  addProviderTiles("Esri.WorldImagery", group = "Satellite") %>%
  addProviderTiles("Stamen.TonerLite", group = "Toner Lite") %>%
  addPolylines(data = easy_trail, 
               label = ~name, group = "Easy Trails") %>% 
  addPolylines(data = medium_trail, 
               label = ~name, group = "Medium Trails") %>% 
  addPolylines(data = hard_trail, 
               label = ~name, group = "Hard Trails") %>% 
  addPolylines(data = trails , 
               color = ~qpal(trail_cont$level), 
               label = ~name , group = "All Trails") %>%
  addLegend("bottomright", pal = qpal, 
            values = ~level, 
            title = "Difficulty (NPS Difficulty Scale)") %>%
            #labFormat = labelFormat(suffix = " NPS Difficulty Scale"))
    addLayersControl(
    baseGroups = c("OpenStreetMap", "Topography", "Satellite", "Toner Lite"),
    overlayGroups = c("All Trails" , "Easy Trails" , "Medium Trails" , "Hard Trails") ,
    options = layersControlOptions(collapsed = FALSE)
  ) 
```


```{r Finding the number of Intersections per Trail}
ind_trail <- function(name_arg) {
  macleish_layers[["trails"]] %>%
    filter(name == name_arg)
}

int_trail <- function(trail_name) {
  trail_name %>%
    st_intersects(macleish_layers[["contours_3m"]], sparse = FALSE)
}

num_int <- function(true_int) {
  length(true_int[true_int == TRUE])
}

number_int <- function(t_name) {
  num_int(int_trail(ind_trail(t_name)))
}

number_int("Driveway")
number_int("Easy Out")
number_int("entry trail")
number_int("Vernal Pool Loop")
number_int("Porcupine Trail")
number_int("Popular Hill Road")
number_int("Eastern Loop")
number_int("Western Loop")
number_int("Snowmobile Trail")
```
